timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
title: MatchMaker MVP UI
domain: mm.dicax.org
layout: default
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .vs/
  - _site/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"   
sass:
  style: expanded
